security:
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }
        our_db_provider:
                    entity:
                        class: App\Entity\User
                        property: username
                        manager_name: customer
    encoders:
        App\Entity\User: bcrypt
    firewalls:
     dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
     main:
                        anonymous: true
                        form_login:
                           login_path: login
                           check_path: login
                           csrf_parameter: _csrf_security_token
                           csrf_token_id: a_private_string
                        logout:
                            path: /logout
                            target: /
                        pattern:    ^/
                        provider: our_db_provider
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }